type Food {
  _id: ID
  name: String!
  price: Int!
  shift: Boolean!
  extra: [String]
  side: [String]
}

type Drink {
  _id: ID
  name: String!
  price: Int!
  shift: Boolean!
}

type Order {
  _id: ID
  food: [Food]!
  drink: [Drink]!
  total: Int!
  client: String
  employee: User!
  extra: [Extra]
  side: [Side]
  table: Int
}

type Extra {
  _id: ID
  name: String!
  price: String!
}

type Side {
  _id: ID
  name: String!
  price: String!
}

type User {
  _id: ID
  username: String! @unique
  password: String!
}

type Token {
  token: String!
}

type Query {
  getUser: User
  getCurrentUser: User
  getDrinkList: [Drink]!
  getFoodList: [Food]!
  getOrderList: [Order]!
  getExtraList: [Extra]
  getSideList: [Side]
}

type Mutation {
  signinUser(username: String!, password: String!): Token
  signupUser(username: String!, password: String!): Token
  addExtra(name: String!, price: Int!): Extra!
  addSide(name: String!, price: Int!): Side!
  addDrink(name: String!, price: Int!): Drink!
  addFood(name: String!, price: Int!, shift: Boolean!): Food!
  addOrder(
    food: ID!
    drink: ID!
    total: Int!
    client: String
    employee: ID!
    extra: [ID]
    side: [ID]
    table: Int
  ): Order!
}
