type Product {
  _id: ID
  name: String!
  price: Int!
  section: String!
}

type Order {
  _id: ID
  table: Int!
  employee: ID!
  status: Boolean!
  listOfProducts: [Product]
}

type User {
  _id: ID
  username: String!
  employee: Int!
}

type Query {
  getProductsList: [Product]!
  getOrderList: [Order]
  getUserList: [User]!
}

type Mutation {
  addUser(username: String!, employee: Int!): User!
  addProduct(name: String!, price: Int!, section: String!): Product!
  addOrder(table: Int!, employee: ID!, status: Boolean!): Order!
}
